#!/bin/bash
#JOB OUTPUT STATUS

HOST=${SENSU_HOST:-'127.0.0.1'}
PORT=${SENSU_PORT:-'3030'}

STATUS=${EXIT_CODE:-2}
if [[ $STATUS -ne 0 ]]; then
    STATUS=2
fi

if [ -z "$END" ]; then 
    END=$(date +"%Y-%m-%dT%H:%M:%SZ")
fi

DATA=$(dockerize -template /app/templates/sensu.tmpl)

RESULT=$(echo "$DATA" | nc $HOST $PORT)
if [[ $RESULT == 'invalid' ]]; then
    OUTPUT="Netcat failure of $RESULT"
    DATA=$(dockerize -template /app/templates/sensu.tmpl)
    RESULT=$(echo "$DATA" | nc $HOST $PORT)
fi
