#!/bin/bash
#JOB OUTPUT STATUS

HOST=${SENSU_HOST:-'127.0.0.1'}
PORT=${SENSU_PORT:-'3030'}
KIBANA=${KIBANA_HOST}


STATUS=$EXIT_CODE
if [[ $EXIT_CODE -ne 0 ]]; then
    STATUS=2
fi

DATA=$(dockerize -template /app/templates/sensu.tmpl)

RESULT=$(echo "$DATA" | nc $HOST $PORT)
if [[ $RESULT == 'invalid' ]]; then
    OUTPUT="Netcat failure of $RESULT"
    DATA=$(dockerize -template /app/templates/sensu.tmpl)
    RESULT=$(echo "$DATA" | nc $HOST $PORT)
fi
