#!/bin/bash
set -a
JOB=$1
source /etc/default/runner
source /etc/default/$JOB; JOB_EXISTS=$?
if [ $JOB_EXISTS -ne 0 ]; then
    echo "The specified job does not exist [${JOB}]"
    exit 1
fi

#Ensure we have a lock to run
case "$LOCKER" in
    consul)
        export CONSUL_HOST; /app/lockers/cronsul $JOB true #Run this in a subshell unlike everything else
        LOCKED=$?
        ;;
    *)
      echo "[$JOB] Skipping lock check"
      LOCKED=0
esac

if [ $LOCKED -eq 0 ]; then
    #Run our commands
    START=$(date +"%Y-%m-%dT%H:%M:%SZ")
    echo "[$JOB] Running @ $START"
    . /app/runners/$RUNNER

    if [ "$EXIT_CODE" != 0 ] && [ $ALERTER ] ; then
      . /app/alerters/$ALERTER
    fi
else
    echo "[$JOB] Locked via ${LOCKER}"
fi

case "$LOCKER" in
    consul)
        export CONSUL_HOST; /app/lockers/cronsul-cleanup > /dev/null
        ;;
    *)
esac
