#!/bin/bash
export KUBERNETES_MASTER

set -e

if [[ "$KUBERNETES_MASTER" == *"https"* || "$KUBERNETES_MASTER" == *"443"* ]]; then
  KUBE_TOKEN=$(</var/run/secrets/kubernetes.io/serviceaccount/token)
  MASTER_VERSION=$(curl -sSk -H "Authorization: Bearer $KUBE_TOKEN" $KUBERNETES_MASTER/version |  grep -i gitVersion | grep -o v[0-9]*\\.[0-9]*.\\.[0-9]*)
else
  MASTER_VERSION=$(curl -s $KUBERNETES_MASTER/version |  grep -i gitVersion | grep -o v[0-9]*\\.[0-9]*.\\.[0-9]*)
fi
LOCAL_VERSION=$(kubectl version --client | grep -i gitVersion | grep -o v[0-9]*\\.[0-9]*.\\.[0-9]*)

test "$MASTER_VERSION" == "$LOCAL_VERSION" || ( echo "Client/Server K8S mismatch. Downloading $MASTER_VERSION" &&
  curl -SL https://storage.googleapis.com/kubernetes-release/release/$MASTER_VERSION/bin/linux/amd64/kubectl -o /usr/local/bin/kubectl &&\
  chmod +x /usr/local/bin/kubectl)
