#!/bin/bash

#We don't currently support a seperate reaper

docker-compose -f /app/compose/$JOB.yaml up

if [ "$FOLLOW" ] ; then
  docker-compose -f /app/compose/$JOB.yaml logs
  EXIT_CODE=$(docker inspect  --format='{{.State.ExitCode}}' compose_${JOB}_1)
  docker-compose -f /app/compose/$JOB.yaml rm -f > /dev/null
fi
