#!/bin/bash
# Set KUBERNETES_MASTER to the URL of your cluster example http://kubemaster:8080
export KUBERNETES_MASTER
NODE_SELECTOR=${NODE_SELECTOR:=""}
PULL_POLICY=${PULL_POLICY:=""}

. /app/processor/reap && unset EXIT_CODE

compose2kube \
  -compose-file /app/compose/$JOB.yaml \
  -pull-policy="${PULL_POLICY}" \
  -node-selector="${NODE_SELECTOR}" \
  -output-dir k8s_${JOB} > /dev/null

if kubectl create -f k8s_${JOB} &> /dev/null ; then
  rm -rf k8s_${JOB}
else
  OUTPUT="Could not create pod. $OUTPUT"
  if [ "$IGNORE_OVERRUN" = true ] ; then
    echo "[${JOB}] - IGNORING OVERRUN - will not alert"
    EXIT_CODE=0
  else
    EXIT_CODE=100
  fi
  return
fi

#Ensure the pod is actually registered. Avoids a possible race condition
until kubectl get jobs $JOB &> /dev/null
do
  sleep 0.1
done

if [ "$FOLLOW" != true ] ; then
  OUTPUT="Running"
  EXIT_CODE=0
else
  STATUS='Pending'
  while [ "$STATUS" == "Pending" ]
  do
    . /app/processor/reap
  done

  kubectl logs -f $JOB_LOWERCASE &

  while [ -z "$EXIT_CODE" ]
  do
    . /app/processor/reap
  done
fi
